Updated to latest espmake

diff --git a/esphome/Makefile b/esphome/Makefile
--- a/esphome/Makefile
+++ b/esphome/Makefile
@@ -1,25 +1,14 @@
-# This Makefile runs dehash on $SRCS so that they can use c-preprocessor
-# directives and C-style comments if needed.  It generates proj.$(PROJTAG).yaml.
-#
-# 'make clean' removes the generated yaml.
-#
-# The yaml file $(MAIN) defaults to main.yaml and can be set by
-# editting it below or from the command line: make MAIN=my_main.yaml
-#
-# C-preprocessed yaml files are stored in directory $(PROJDIR).
-# $(PROJDIR) defaults to proj.$(PROJTAG). $(PROJTAG) defaults to "0". 
-# C-preprocessor ifdefs can be used to generate many different yaml
-# projects from the same directory. It is possible to use multiple
-# PROJTAGs to generate multiple yaml projects from the same yaml
-# files.  See the example in this directory, especially ./config.h,
-# which demonstrates ypp used on an esphome file.
-#
-# The file proj.$(PROJTAG).yaml can be inspected if esphome indicates
-# any specific line numbers have syntax errors. 
+# This Makefile is based on https://github.com/maartenwrs/espmake
+# 
+# A convenience c-preprocessor define _PROJTAG$(PROJTAG) is defined so that
+# project-specific yaml can be written inside, for example, #if _PROJTAG_foo
+# / #endif blocks, when PROJTAG is set to "foo".
 # 
 # A convenience c-preprocessor define _USER_$(USER) is defined so that
 # personal yaml can be written inside, for example, #if _USER_maarten
 # / #endif blocks, if your userid is 'maarten'.
+#
+# Please see https://github.com/maartenwrs/espmake/blob/main/README.md for more details.
 
 MAIN	= main.yaml
 SRCS	= $(wildcard *.yaml)
@@ -28,47 +17,86 @@ SRCS	= $(wildcard *.yaml)
 ifneq (x$(suffix $(MAIN)),x.yaml)
   $(error "The suffix of $(MAIN) yaml file must be .yaml")
 endif
+ifeq ($(shell test -e $(MAIN) || echo -n no),no)
+  $(error "$(MAIN) not found (MAIN=xxx.yaml argument intended?)")
+endif
 
+ifneq (x$(suffix $(MAIN)),x.yaml)
+  $(error "The suffix of $(MAIN) yaml file must be .yaml")
+endif
+
+OUTDIR	= .
 PROJTAG	= 0
-PROJDIR	= proj.$(PROJTAG)
-DEFS    = -I$(PROJDIR) -I. -D_PROJTAG_$(PROJTAG)=1 -D_USER_$(USER)=1
+PREFIX	= myProj_
+PROJDIR	= $(OUTDIR)/$(PREFIX)$(PROJTAG)
+CPPINCS = -I$(PROJDIR) -I.
+CPPDEFS = -D_PROJTAG_$(PROJTAG)=1 -D_USER_$(USER)=1
 
 _MAIN	= $(PROJDIR).yaml
-_YAMLS	= $(addprefix $(PROJDIR)/,$(filter-out $(wildcard proj.*.yaml),$(SRCS)))
+_YAMLS	= $(addprefix $(PROJDIR)/,$(filter-out $(wildcard $(PREFIX)*.yaml),$(SRCS)))
 
-DEHASH	= ./dehash/dehash
-CPP	= gcc -x c -E -P -undef -nostdinc $(DEFS) 
+DEHASH	= $(OUTDIR)/dehash/dehash.sh --cpp
+CPP	= gcc -x c -E -P -undef -nostdinc $(CPPINCS) $(CPPDEFS) 
 
-all:	 dehash $(_YAMLS) $(_MAIN)
+all:	$(OUTDIR)/dehash $(PROJDIR) $(_YAMLS) $(_MAIN)
+	-@if [ "$(OUTDIR)" != "." -a -f "secrets.yaml" ]; then 		   \
+	    if [ -L "$(OUTDIR)/secrets.yaml" ]; then 			   \
+	    	rm -f $(OUTDIR)/secrets.yaml;				   \
+		echo "re-linking $(OUTDIR)/secrets.yaml";		   \
+	    else							   \
+		echo "linking $(OUTDIR)/secrets.yaml";			   \
+	    fi;								   \
+	    ln -s $(PREFIX)$(PROJTAG)/secrets.yaml $(OUTDIR)/secrets.yaml; \
+	fi
+	@echo "$(_MAIN) is up to date and ready for commands such as:"
+	@echo "esphome config  $(_MAIN)"
+	@echo "esphome compile $(_MAIN)"
+	@echo "esphome upload  $(_MAIN)"
 
-$(_MAIN) $(_YAMLS): Makefile
+$(_MAIN) $(_YAMLS): $(OUTDIR)/dehash Makefile
 
-$(_MAIN): $(PROJDIR)/$(MAIN)
-	@echo "Generating $@"
+$(_MAIN): $(PROJDIR)/$(MAIN) $(_YAMLS)
+	@echo "Generating $@ from dehashed files in $(PROJDIR)/"
 	$(CPP) -MD -MP -MT $@ -MF $<.d $< > $@
+
+$(OUTDIR):
+	-mkdir -p $@
 
 $(PROJDIR):
 	-mkdir -p $@
 
 $(PROJDIR)/%.yaml: %.yaml
-	$(DEHASH) --cpp --outdir $(PROJDIR) $<
+	$(DEHASH) $< > $@
 
 -include $(wildcard $(PROJDIR)/*.d)
 
 clean:
 	rm -rf $(PROJDIR) $(_MAIN)
+	@if [ "$(OUTDIR)" != "." -a -f "secrets.yaml" ]; then 	\
+	    if [ -L "$(OUTDIR)/secrets.yaml" ]; then 		\
+	    	echo "rm $(OUTDIR)/secrets.yaml";		\
+	    	rm -f $(OUTDIR)/secrets.yaml;			\
+	    fi;							\
+	fi
 
-realclean: 
-	rm -rf .esphome dehash ./.dehash
+realclean: clean
+	rm -rf $(OUTDIR)/dehash .esphome
 
-.PHONY:    clean realclean all update
-.PRECIOUS: $(PROJDIR) dehash
+.PHONY:    clean realclean update
+.PRECIOUS: $(PROJDIR) $(OUTDIR) $(OUTDIR)/dehash
 
-dehash:
-	git clone git@github.com:maartenwrs/dehash
+$(OUTDIR)/dehash:
+	-@mkdir -p $(OUTDIR)
+	cd $(OUTDIR); git clone git@github.com:maartenwrs/dehash
 
-# update this Makefile from github. Danger if you modified it!
+# pull dehash repo and this Makefile from github
 update:
-	mv Makefile Makefile.old
-	curl https://raw.githubusercontent.com/maartenwrs/espmake/main/Makefile >Makefile
+	-@if [ -d "$(OUTDIR)/dehash" ]; then 			\
+		echo "Updating git repo $(OUTDIR)/dehash";	\
+		cd $(OUTDIR)/dehash; git pull; 			\
+	fi
+	-@curl https://raw.githubusercontent.com/maartenwrs/espmake/main/Makefile >Makefile.new 2> /dev/null
+	-@echo "Latest espmake Makefile downloaded as Makefile.new"
+	-@echo "Changes from ./Makefile to latest espmake Makefile are:"
+	-diff Makefile Makefile.new
 
